### ISSUE TITLE
来，讨论呀！

### ISSUE THREAD

**Issue by git-yusteven** [git-yusteven/openit#44]
Here it is ！

**Comment by Mabbs** [comment]
很不错，建议在readme里直接加上订阅地址，例如：https://cdn.jsdelivr.net/gh/git-yusteven/openit/b

**Comment by git-yusteven** [comment]
> 很不错，建议在readme里直接加上订阅地址，例如：https://cdn.jsdelivr.net/gh/git-yusteven/openit/b
我就去改一改

**Comment by Mabbs** [comment]
emmmm之所以推荐用jsdelivr主要是因为国内方便访问，如果直接用github的链接没翻的时候会更新失败。

**Comment by git-yusteven** [comment]
> emmmm之所以推荐用jsdelivr主要是因为国内方便访问，如果直接用github的链接没翻的时候会更新失败。

你的意思是免翻墙呀，我还以为只是放个链接上去😂
